version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: coworking_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cattaneo28
      MYSQL_DATABASE: coworking
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro

  backend:
    build: .
    container_name: coworking_backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/coworking?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    # Si tu backend necesita ver archivos locales (opcional):
    volumes:
      - .:/app

volumes:
  db_data: