spring.datasource.url=postgresql://coworking_db_pubd_user:VNkqUr9IJ6RcC3s8HaKbj9pDPnzmqOTE@dpg-d4c8gr8dl3ps73bbcrig-a/coworking_db_pubd
spring.datasource.username=coworking_db_pubd_user
spring.datasource.password=VNkqUr9IJ6RcC3s8HaKbj9pDPnzmqOTE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=5432
